[project]
name = "notes-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "basedpyright>=1.29.5",
    "fastapi[standard]>=0.115.14",
    "ruff>=0.12.1",
    "sqlalchemy>=2.0.41",
]
